server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop


#zuul:
#  routes:
#    users:
#      path: /api/v1/users/**
#      url: http://localhost:8080/api/users
#    cars:
#      path: /api/v2/cars/**
#      url: http://localhost:8080/api/cars

#zuul:
#  routes:
#    users:
##      path: /api/v1/users/**
#      url: http://localhost:8080/api/v1/users/
zuul:
  prefix: /api
  routes:
    users:
      path: /v1/users/**
      url: http://localhost:8080/api/users/

