server:
  port: 0

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: cars-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}